[package]
name = "audioserve"
version = "0.14.0"
authors = ["Ivan <ivan.zderadicka@gmail.com>"]
edition = "2018"

[workspace]
members = ["crates/*"]

[dependencies]
env_logger = "0.8"
log = {version="0.4", features = ["release_max_level_info"]}
hyper = {version="0.14", features = ["full"]}
headers = "0.3"
futures = "0.3"
mime = "0.3"
mime_guess = "2.0"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
clap = "2"
lazy_static = "1.4"
thiserror = "1.0"
anyhow = "1.0"
url = "2.1"
percent-encoding = "2.1"
num_cpus = "1.13"
ring = "0.16"
data-encoding = "2.2"
regex = "1.3"
tokio = {version="1.0", features=["full"]}

dirs = "3.0"
csv = "1.1"
unicase = "2.6"
unicase_serde = "0.1.0"
linked-hash-map = {git="https://github.com/izderadicka/linked-hash-map.git", version="0.5.3", features=["serde_impl"]}

# for tls
tokio-native-tls = {version="0.3", optional=true}
native-tls = {version="0.2", optional=true}
async-stream ={version="0.3", optional=true}

cachedirtree = {path="crates/cachedirtree", optional=true}

bytes = {version="1.0", optional=true}

tokio-util = {version="0.6", optional=true}

media_info = {path="crates/media_info"}

[dependencies.simple-file-cache]
path="crates/file-cache"
features=["asynch"]
optional=true

[dependencies.async-tar]
path="crates/async-tar"
optional=true

[dependencies.websock]
path="crates/websock"
optional = true

[target.'cfg(unix)'.dependencies]
nix = "0.19"

[features]
default = ["tls", "symlinks","search-cache", "folder-download", "shared-positions"]
tls=["tokio-native-tls", "native-tls", "async-stream"]
symlinks=["cachedirtree/symlinks"]
search-cache=["cachedirtree"]
transcoding-cache=["simple-file-cache", "bytes", "tokio-util"]
folder-download = ["async-tar"]
static = ["media_info/static"]
partially-static = ["media_info/partially-static"]
shared-positions = ["websock"]

[profile.release]
lto = true
codegen-units = 1

[dev-dependencies]
reqwest = {version="0.11", features=['blocking', 'json']}
escargot = "0.5" 
