[package]
name = "simple-file-cache"
version = "0.2.1"
authors = ["Ivan <ivan.zderadicka@gmail.com>"]
edition = "2018"

[dependencies]
linked-hash-map = "0.5.3"
#filetime = "0.2"
rand = "0.8"
data-encoding = "2.2"
thiserror ="1.0"
log = "0.4"
byteorder = "1.3"

tokio = { version="1.0", optional=true, features=[ "rt", "fs"] }


[features]
asynch = ["tokio"]

[dev-dependencies]
env_logger = "0.8"
tempfile ="3.1"
tokio = { version="1.0", features=["io-util", "macros",] }


